#!/usr/bin/env bash
# Junie has no native per-rule file format. Cross-cutting rules live in
# .junie/AGENTS.md (generated by sync-agent-guidelines from AGENTS.md).
#
# This script is intentionally a no-op with a log message. -i and -o are
# accepted for a uniform CLI (e.g. sync-all); -i is typically rules/ or any
# existing directory.
#
# Usage:
#   sync-rules.sh -i <ignored_source_dir> -o <output_root> [--clean] [--help]
#
#   --clean  No effect (per-rule content is in sync-agent-guidelines). Accepted
#            for a uniform CLI with other sync-rules.
#
# Examples (input directory ignored; output = project root):
#   sync-rules.sh -i "$PWD/examples/rules" -o "$PWD"
#   sync-rules.sh -i "$PWD/examples/rules" -o "$PWD" --clean

COMMON="$(cd "$(dirname "${BASH_SOURCE[0]}")/../common" && pwd)/common.sh"
source "$COMMON"

parse_io_args "$@"
to_abs_dir "$INPUT" >/dev/null
to_abs_dir "$OUTPUT" >/dev/null

echo "junie rules -> skipped (per-rule content is merged into .junie/AGENTS.md by sync-agent-guidelines)"
