#!/usr/bin/env bash
# Sync rules from <rules_dir>/*.md to
# <output_root>/.github/instructions/<name>.instructions.md.
#
# Translation of generic source fields:
#   always-apply: true  ->  applyTo: "**"
#   applies-to: "..."   ->  applyTo: "..."
#   neither present     ->  applyTo: "**"
#
# Usage:
#   sync-rules.sh -i <rules_dir> -o <output_root> [--items name1,name2] [--clean] [--help]
#
#   --clean  Remove all files under .github/instructions/ before syncing
#            (only files generated by this script should live there).
#
# Examples (project root = output; input = examples/rules):
#   sync-rules.sh -i "$PWD/examples/rules" -o "$PWD"
#   sync-rules.sh -i "$PWD/examples/rules" -o "$PWD" --items java-conventions,commit-style

COMMON="$(cd "$(dirname "${BASH_SOURCE[0]}")/../common" && pwd)/common.sh"
source "$COMMON"

parse_io_args "$@"
INPUT_DIR="$(to_abs_dir "$INPUT")"
OUTPUT_DIR="$(to_abs_dir "$OUTPUT")"

if [[ "$CLEAN" == "true" ]]; then
  clean_dir_contents "$OUTPUT_DIR/.github/instructions"
  echo "copilot rules: cleaned $OUTPUT_DIR/.github/instructions/"
fi

copilot_rule() {
  local name="$1" src="$2"
  local dst="$OUTPUT_DIR/.github/instructions/$name.instructions.md"
  local applies always applyTo
  applies="$(extract_field "$src" applies-to)"
  always="$(extract_field "$src" always-apply)"
  if [[ "$always" == "true" ]]; then
    applyTo='**'
  elif [[ -n "$applies" ]]; then
    applyTo="$applies"
  else
    applyTo='**'
  fi
  mkdir -p "$(dirname "$dst")"
  {
    printf -- '---\n'
    printf 'applyTo: "%s"\n' "$applyTo"
    printf -- '---\n\n'
    strip_frontmatter "$src"
  } > "$dst"
  echo "copilot rule -> $dst"
}

sync_items "$INPUT_DIR" file copilot_rule
